/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as PreviewRouteRouteImport } from './routes/preview/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as protectedLeaderboardRouteRouteImport } from './routes/(protected)/leaderboard/route'
import { Route as protectedLinksRouteRouteImport } from './routes/(protected)/links/route'
import { Route as protectedPackagePurchaseRouteRouteImport } from './routes/(protected)/package-purchase/route'
import { Route as protectedPartnersRouteRouteImport } from './routes/(protected)/partners/route'
import { Route as protectedSocialRouteRouteImport } from './routes/(protected)/social/route'
import { Route as protectedStatsRouteRouteImport } from './routes/(protected)/stats/route'
import { Route as protectedTeamRouteRouteImport } from './routes/(protected)/team/route'
import { Route as PreviewDashboardRouteRouteImport } from './routes/preview/dashboard/route'
import { Route as PreviewLeaderboardRouteRouteImport } from './routes/preview/leaderboard/route'
import { Route as PreviewLinksRouteRouteImport } from './routes/preview/links/route'
import { Route as PreviewPartnersRouteRouteImport } from './routes/preview/partners/route'
import { Route as PreviewTeamRouteRouteImport } from './routes/preview/team/route'
import { Route as authRefIdRouteImport } from './routes/(auth)/ref.$id'
import { Route as protectedIncomeMagicGoldMatrixRouteImport } from './routes/(protected)/_income/magic-gold-matrix'
import { Route as protectedIncomeMagicLevelRouteImport } from './routes/(protected)/_income/magic-level'
import { Route as protectedIncomeSponsorMagicRouteImport } from './routes/(protected)/_income/sponsor-magic'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedDashboardProgramRouteRouteImport } from './routes/(protected)/dashboard/$program/route'
import { Route as protectedPackagePurchaseIndexRouteImport } from './routes/(protected)/package-purchase/index'
import { Route as protectedPackagePurchaseMagicGoldMatrixRouteImport } from './routes/(protected)/package-purchase/magic-gold-matrix'
import { Route as protectedPackagePurchaseMagicLevelRouteImport } from './routes/(protected)/package-purchase/magic-level'
import { Route as protectedPackagePurchaseSponsorMagicRouteImport } from './routes/(protected)/package-purchase/sponsor-magic'
import { Route as PreviewIncomeMagicGoldMatrixRouteImport } from './routes/preview/_income/magic-gold-matrix'
import { Route as PreviewIncomeMagicLevelRouteImport } from './routes/preview/_income/magic-level'
import { Route as PreviewIncomeSponsorMagicRouteImport } from './routes/preview/_income/sponsor-magic'
import { Route as PreviewDashboardIndexRouteImport } from './routes/preview/dashboard/index'
import { Route as PreviewDashboardProgramRouteRouteImport } from './routes/preview/dashboard/$program/route'
import { Route as protectedDashboardProgramIndexRouteImport } from './routes/(protected)/dashboard/$program/index'
import { Route as protectedDashboardProgramLevelRouteImport } from './routes/(protected)/dashboard/$program/$level'
import { Route as PreviewDashboardProgramIndexRouteImport } from './routes/preview/dashboard/$program/index'
import { Route as PreviewDashboardProgramLevelRouteImport } from './routes/preview/dashboard/$program/$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRouteRoute = PreviewRouteRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedLeaderboardRouteRoute =
  protectedLeaderboardRouteRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedLinksRouteRoute = protectedLinksRouteRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPackagePurchaseRouteRoute =
  protectedPackagePurchaseRouteRouteImport.update({
    id: '/package-purchase',
    path: '/package-purchase',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedPartnersRouteRoute = protectedPartnersRouteRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSocialRouteRoute = protectedSocialRouteRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedStatsRouteRoute = protectedStatsRouteRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedTeamRouteRoute = protectedTeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => protectedRouteRoute,
} as any)
const PreviewDashboardRouteRoute = PreviewDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const PreviewLeaderboardRouteRoute = PreviewLeaderboardRouteRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const PreviewLinksRouteRoute = PreviewLinksRouteRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const PreviewPartnersRouteRoute = PreviewPartnersRouteRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const PreviewTeamRouteRoute = PreviewTeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const authRefIdRoute = authRefIdRouteImport.update({
  id: '/ref/$id',
  path: '/ref/$id',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedIncomeMagicGoldMatrixRoute =
  protectedIncomeMagicGoldMatrixRouteImport.update({
    id: '/_income/magic-gold-matrix',
    path: '/magic-gold-matrix',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedIncomeMagicLevelRoute =
  protectedIncomeMagicLevelRouteImport.update({
    id: '/_income/magic-level',
    path: '/magic-level',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedIncomeSponsorMagicRoute =
  protectedIncomeSponsorMagicRouteImport.update({
    id: '/_income/sponsor-magic',
    path: '/sponsor-magic',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDashboardRouteRoute,
} as any)
const protectedDashboardProgramRouteRoute =
  protectedDashboardProgramRouteRouteImport.update({
    id: '/$program',
    path: '/$program',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedPackagePurchaseIndexRoute =
  protectedPackagePurchaseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedPackagePurchaseRouteRoute,
  } as any)
const protectedPackagePurchaseMagicGoldMatrixRoute =
  protectedPackagePurchaseMagicGoldMatrixRouteImport.update({
    id: '/magic-gold-matrix',
    path: '/magic-gold-matrix',
    getParentRoute: () => protectedPackagePurchaseRouteRoute,
  } as any)
const protectedPackagePurchaseMagicLevelRoute =
  protectedPackagePurchaseMagicLevelRouteImport.update({
    id: '/magic-level',
    path: '/magic-level',
    getParentRoute: () => protectedPackagePurchaseRouteRoute,
  } as any)
const protectedPackagePurchaseSponsorMagicRoute =
  protectedPackagePurchaseSponsorMagicRouteImport.update({
    id: '/sponsor-magic',
    path: '/sponsor-magic',
    getParentRoute: () => protectedPackagePurchaseRouteRoute,
  } as any)
const PreviewIncomeMagicGoldMatrixRoute =
  PreviewIncomeMagicGoldMatrixRouteImport.update({
    id: '/_income/magic-gold-matrix',
    path: '/magic-gold-matrix',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewIncomeMagicLevelRoute = PreviewIncomeMagicLevelRouteImport.update({
  id: '/_income/magic-level',
  path: '/magic-level',
  getParentRoute: () => PreviewRouteRoute,
} as any)
const PreviewIncomeSponsorMagicRoute =
  PreviewIncomeSponsorMagicRouteImport.update({
    id: '/_income/sponsor-magic',
    path: '/sponsor-magic',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewDashboardIndexRoute = PreviewDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewDashboardRouteRoute,
} as any)
const PreviewDashboardProgramRouteRoute =
  PreviewDashboardProgramRouteRouteImport.update({
    id: '/$program',
    path: '/$program',
    getParentRoute: () => PreviewDashboardRouteRoute,
  } as any)
const protectedDashboardProgramIndexRoute =
  protectedDashboardProgramIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardProgramRouteRoute,
  } as any)
const protectedDashboardProgramLevelRoute =
  protectedDashboardProgramLevelRouteImport.update({
    id: '/$level',
    path: '/$level',
    getParentRoute: () => protectedDashboardProgramRouteRoute,
  } as any)
const PreviewDashboardProgramIndexRoute =
  PreviewDashboardProgramIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PreviewDashboardProgramRouteRoute,
  } as any)
const PreviewDashboardProgramLevelRoute =
  PreviewDashboardProgramLevelRouteImport.update({
    id: '/$level',
    path: '/$level',
    getParentRoute: () => PreviewDashboardProgramRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/leaderboard': typeof protectedLeaderboardRouteRoute
  '/links': typeof protectedLinksRouteRoute
  '/package-purchase': typeof protectedPackagePurchaseRouteRouteWithChildren
  '/partners': typeof protectedPartnersRouteRoute
  '/social': typeof protectedSocialRouteRoute
  '/stats': typeof protectedStatsRouteRoute
  '/team': typeof protectedTeamRouteRoute
  '/preview/dashboard': typeof PreviewDashboardRouteRouteWithChildren
  '/preview/leaderboard': typeof PreviewLeaderboardRouteRoute
  '/preview/links': typeof PreviewLinksRouteRoute
  '/preview/partners': typeof PreviewPartnersRouteRoute
  '/preview/team': typeof PreviewTeamRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/$program': typeof protectedDashboardProgramRouteRouteWithChildren
  '/preview/dashboard/$program': typeof PreviewDashboardProgramRouteRouteWithChildren
  '/ref/$id': typeof authRefIdRoute
  '/magic-gold-matrix': typeof protectedIncomeMagicGoldMatrixRoute
  '/magic-level': typeof protectedIncomeMagicLevelRoute
  '/sponsor-magic': typeof protectedIncomeSponsorMagicRoute
  '/package-purchase/magic-gold-matrix': typeof protectedPackagePurchaseMagicGoldMatrixRoute
  '/package-purchase/magic-level': typeof protectedPackagePurchaseMagicLevelRoute
  '/package-purchase/sponsor-magic': typeof protectedPackagePurchaseSponsorMagicRoute
  '/preview/magic-gold-matrix': typeof PreviewIncomeMagicGoldMatrixRoute
  '/preview/magic-level': typeof PreviewIncomeMagicLevelRoute
  '/preview/sponsor-magic': typeof PreviewIncomeSponsorMagicRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/package-purchase/': typeof protectedPackagePurchaseIndexRoute
  '/preview/dashboard/': typeof PreviewDashboardIndexRoute
  '/dashboard/$program/$level': typeof protectedDashboardProgramLevelRoute
  '/preview/dashboard/$program/$level': typeof PreviewDashboardProgramLevelRoute
  '/dashboard/$program/': typeof protectedDashboardProgramIndexRoute
  '/preview/dashboard/$program/': typeof PreviewDashboardProgramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRouteRouteWithChildren
  '/leaderboard': typeof protectedLeaderboardRouteRoute
  '/links': typeof protectedLinksRouteRoute
  '/partners': typeof protectedPartnersRouteRoute
  '/social': typeof protectedSocialRouteRoute
  '/stats': typeof protectedStatsRouteRoute
  '/team': typeof protectedTeamRouteRoute
  '/preview/leaderboard': typeof PreviewLeaderboardRouteRoute
  '/preview/links': typeof PreviewLinksRouteRoute
  '/preview/partners': typeof PreviewPartnersRouteRoute
  '/preview/team': typeof PreviewTeamRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/ref/$id': typeof authRefIdRoute
  '/magic-gold-matrix': typeof protectedIncomeMagicGoldMatrixRoute
  '/magic-level': typeof protectedIncomeMagicLevelRoute
  '/sponsor-magic': typeof protectedIncomeSponsorMagicRoute
  '/package-purchase/magic-gold-matrix': typeof protectedPackagePurchaseMagicGoldMatrixRoute
  '/package-purchase/magic-level': typeof protectedPackagePurchaseMagicLevelRoute
  '/package-purchase/sponsor-magic': typeof protectedPackagePurchaseSponsorMagicRoute
  '/preview/magic-gold-matrix': typeof PreviewIncomeMagicGoldMatrixRoute
  '/preview/magic-level': typeof PreviewIncomeMagicLevelRoute
  '/preview/sponsor-magic': typeof PreviewIncomeSponsorMagicRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/package-purchase': typeof protectedPackagePurchaseIndexRoute
  '/preview/dashboard': typeof PreviewDashboardIndexRoute
  '/dashboard/$program/$level': typeof protectedDashboardProgramLevelRoute
  '/preview/dashboard/$program/$level': typeof PreviewDashboardProgramLevelRoute
  '/dashboard/$program': typeof protectedDashboardProgramIndexRoute
  '/preview/dashboard/$program': typeof PreviewDashboardProgramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/preview': typeof PreviewRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(protected)/leaderboard': typeof protectedLeaderboardRouteRoute
  '/(protected)/links': typeof protectedLinksRouteRoute
  '/(protected)/package-purchase': typeof protectedPackagePurchaseRouteRouteWithChildren
  '/(protected)/partners': typeof protectedPartnersRouteRoute
  '/(protected)/social': typeof protectedSocialRouteRoute
  '/(protected)/stats': typeof protectedStatsRouteRoute
  '/(protected)/team': typeof protectedTeamRouteRoute
  '/preview/dashboard': typeof PreviewDashboardRouteRouteWithChildren
  '/preview/leaderboard': typeof PreviewLeaderboardRouteRoute
  '/preview/links': typeof PreviewLinksRouteRoute
  '/preview/partners': typeof PreviewPartnersRouteRoute
  '/preview/team': typeof PreviewTeamRouteRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(protected)/dashboard/$program': typeof protectedDashboardProgramRouteRouteWithChildren
  '/preview/dashboard/$program': typeof PreviewDashboardProgramRouteRouteWithChildren
  '/(auth)/ref/$id': typeof authRefIdRoute
  '/(protected)/_income/magic-gold-matrix': typeof protectedIncomeMagicGoldMatrixRoute
  '/(protected)/_income/magic-level': typeof protectedIncomeMagicLevelRoute
  '/(protected)/_income/sponsor-magic': typeof protectedIncomeSponsorMagicRoute
  '/(protected)/package-purchase/magic-gold-matrix': typeof protectedPackagePurchaseMagicGoldMatrixRoute
  '/(protected)/package-purchase/magic-level': typeof protectedPackagePurchaseMagicLevelRoute
  '/(protected)/package-purchase/sponsor-magic': typeof protectedPackagePurchaseSponsorMagicRoute
  '/preview/_income/magic-gold-matrix': typeof PreviewIncomeMagicGoldMatrixRoute
  '/preview/_income/magic-level': typeof PreviewIncomeMagicLevelRoute
  '/preview/_income/sponsor-magic': typeof PreviewIncomeSponsorMagicRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/package-purchase/': typeof protectedPackagePurchaseIndexRoute
  '/preview/dashboard/': typeof PreviewDashboardIndexRoute
  '/(protected)/dashboard/$program/$level': typeof protectedDashboardProgramLevelRoute
  '/preview/dashboard/$program/$level': typeof PreviewDashboardProgramLevelRoute
  '/(protected)/dashboard/$program/': typeof protectedDashboardProgramIndexRoute
  '/preview/dashboard/$program/': typeof PreviewDashboardProgramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/dashboard'
    | '/leaderboard'
    | '/links'
    | '/package-purchase'
    | '/partners'
    | '/social'
    | '/stats'
    | '/team'
    | '/preview/dashboard'
    | '/preview/leaderboard'
    | '/preview/links'
    | '/preview/partners'
    | '/preview/team'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$program'
    | '/preview/dashboard/$program'
    | '/ref/$id'
    | '/magic-gold-matrix'
    | '/magic-level'
    | '/sponsor-magic'
    | '/package-purchase/magic-gold-matrix'
    | '/package-purchase/magic-level'
    | '/package-purchase/sponsor-magic'
    | '/preview/magic-gold-matrix'
    | '/preview/magic-level'
    | '/preview/sponsor-magic'
    | '/dashboard/'
    | '/package-purchase/'
    | '/preview/dashboard/'
    | '/dashboard/$program/$level'
    | '/preview/dashboard/$program/$level'
    | '/dashboard/$program/'
    | '/preview/dashboard/$program/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/leaderboard'
    | '/links'
    | '/partners'
    | '/social'
    | '/stats'
    | '/team'
    | '/preview/leaderboard'
    | '/preview/links'
    | '/preview/partners'
    | '/preview/team'
    | '/sign-in'
    | '/sign-up'
    | '/ref/$id'
    | '/magic-gold-matrix'
    | '/magic-level'
    | '/sponsor-magic'
    | '/package-purchase/magic-gold-matrix'
    | '/package-purchase/magic-level'
    | '/package-purchase/sponsor-magic'
    | '/preview/magic-gold-matrix'
    | '/preview/magic-level'
    | '/preview/sponsor-magic'
    | '/dashboard'
    | '/package-purchase'
    | '/preview/dashboard'
    | '/dashboard/$program/$level'
    | '/preview/dashboard/$program/$level'
    | '/dashboard/$program'
    | '/preview/dashboard/$program'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/preview'
    | '/(protected)/dashboard'
    | '/(protected)/leaderboard'
    | '/(protected)/links'
    | '/(protected)/package-purchase'
    | '/(protected)/partners'
    | '/(protected)/social'
    | '/(protected)/stats'
    | '/(protected)/team'
    | '/preview/dashboard'
    | '/preview/leaderboard'
    | '/preview/links'
    | '/preview/partners'
    | '/preview/team'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(protected)/dashboard/$program'
    | '/preview/dashboard/$program'
    | '/(auth)/ref/$id'
    | '/(protected)/_income/magic-gold-matrix'
    | '/(protected)/_income/magic-level'
    | '/(protected)/_income/sponsor-magic'
    | '/(protected)/package-purchase/magic-gold-matrix'
    | '/(protected)/package-purchase/magic-level'
    | '/(protected)/package-purchase/sponsor-magic'
    | '/preview/_income/magic-gold-matrix'
    | '/preview/_income/magic-level'
    | '/preview/_income/sponsor-magic'
    | '/(protected)/dashboard/'
    | '/(protected)/package-purchase/'
    | '/preview/dashboard/'
    | '/(protected)/dashboard/$program/$level'
    | '/preview/dashboard/$program/$level'
    | '/(protected)/dashboard/$program/'
    | '/preview/dashboard/$program/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  PreviewRouteRoute: typeof PreviewRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/leaderboard': {
      id: '/(protected)/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof protectedLeaderboardRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/links': {
      id: '/(protected)/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof protectedLinksRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/package-purchase': {
      id: '/(protected)/package-purchase'
      path: '/package-purchase'
      fullPath: '/package-purchase'
      preLoaderRoute: typeof protectedPackagePurchaseRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/partners': {
      id: '/(protected)/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof protectedPartnersRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/social': {
      id: '/(protected)/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof protectedSocialRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/stats': {
      id: '/(protected)/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof protectedStatsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/team': {
      id: '/(protected)/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof protectedTeamRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/preview/dashboard': {
      id: '/preview/dashboard'
      path: '/dashboard'
      fullPath: '/preview/dashboard'
      preLoaderRoute: typeof PreviewDashboardRouteRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/leaderboard': {
      id: '/preview/leaderboard'
      path: '/leaderboard'
      fullPath: '/preview/leaderboard'
      preLoaderRoute: typeof PreviewLeaderboardRouteRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/links': {
      id: '/preview/links'
      path: '/links'
      fullPath: '/preview/links'
      preLoaderRoute: typeof PreviewLinksRouteRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/partners': {
      id: '/preview/partners'
      path: '/partners'
      fullPath: '/preview/partners'
      preLoaderRoute: typeof PreviewPartnersRouteRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/team': {
      id: '/preview/team'
      path: '/team'
      fullPath: '/preview/team'
      preLoaderRoute: typeof PreviewTeamRouteRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/(auth)/ref/$id': {
      id: '/(auth)/ref/$id'
      path: '/ref/$id'
      fullPath: '/ref/$id'
      preLoaderRoute: typeof authRefIdRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/_income/magic-gold-matrix': {
      id: '/(protected)/_income/magic-gold-matrix'
      path: '/magic-gold-matrix'
      fullPath: '/magic-gold-matrix'
      preLoaderRoute: typeof protectedIncomeMagicGoldMatrixRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/_income/magic-level': {
      id: '/(protected)/_income/magic-level'
      path: '/magic-level'
      fullPath: '/magic-level'
      preLoaderRoute: typeof protectedIncomeMagicLevelRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/_income/sponsor-magic': {
      id: '/(protected)/_income/sponsor-magic'
      path: '/sponsor-magic'
      fullPath: '/sponsor-magic'
      preLoaderRoute: typeof protectedIncomeSponsorMagicRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/$program': {
      id: '/(protected)/dashboard/$program'
      path: '/$program'
      fullPath: '/dashboard/$program'
      preLoaderRoute: typeof protectedDashboardProgramRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/package-purchase/': {
      id: '/(protected)/package-purchase/'
      path: '/'
      fullPath: '/package-purchase/'
      preLoaderRoute: typeof protectedPackagePurchaseIndexRouteImport
      parentRoute: typeof protectedPackagePurchaseRouteRoute
    }
    '/(protected)/package-purchase/magic-gold-matrix': {
      id: '/(protected)/package-purchase/magic-gold-matrix'
      path: '/magic-gold-matrix'
      fullPath: '/package-purchase/magic-gold-matrix'
      preLoaderRoute: typeof protectedPackagePurchaseMagicGoldMatrixRouteImport
      parentRoute: typeof protectedPackagePurchaseRouteRoute
    }
    '/(protected)/package-purchase/magic-level': {
      id: '/(protected)/package-purchase/magic-level'
      path: '/magic-level'
      fullPath: '/package-purchase/magic-level'
      preLoaderRoute: typeof protectedPackagePurchaseMagicLevelRouteImport
      parentRoute: typeof protectedPackagePurchaseRouteRoute
    }
    '/(protected)/package-purchase/sponsor-magic': {
      id: '/(protected)/package-purchase/sponsor-magic'
      path: '/sponsor-magic'
      fullPath: '/package-purchase/sponsor-magic'
      preLoaderRoute: typeof protectedPackagePurchaseSponsorMagicRouteImport
      parentRoute: typeof protectedPackagePurchaseRouteRoute
    }
    '/preview/_income/magic-gold-matrix': {
      id: '/preview/_income/magic-gold-matrix'
      path: '/magic-gold-matrix'
      fullPath: '/preview/magic-gold-matrix'
      preLoaderRoute: typeof PreviewIncomeMagicGoldMatrixRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/_income/magic-level': {
      id: '/preview/_income/magic-level'
      path: '/magic-level'
      fullPath: '/preview/magic-level'
      preLoaderRoute: typeof PreviewIncomeMagicLevelRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/_income/sponsor-magic': {
      id: '/preview/_income/sponsor-magic'
      path: '/sponsor-magic'
      fullPath: '/preview/sponsor-magic'
      preLoaderRoute: typeof PreviewIncomeSponsorMagicRouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/dashboard/': {
      id: '/preview/dashboard/'
      path: '/'
      fullPath: '/preview/dashboard/'
      preLoaderRoute: typeof PreviewDashboardIndexRouteImport
      parentRoute: typeof PreviewDashboardRouteRoute
    }
    '/preview/dashboard/$program': {
      id: '/preview/dashboard/$program'
      path: '/$program'
      fullPath: '/preview/dashboard/$program'
      preLoaderRoute: typeof PreviewDashboardProgramRouteRouteImport
      parentRoute: typeof PreviewDashboardRouteRoute
    }
    '/(protected)/dashboard/$program/': {
      id: '/(protected)/dashboard/$program/'
      path: '/'
      fullPath: '/dashboard/$program/'
      preLoaderRoute: typeof protectedDashboardProgramIndexRouteImport
      parentRoute: typeof protectedDashboardProgramRouteRoute
    }
    '/(protected)/dashboard/$program/$level': {
      id: '/(protected)/dashboard/$program/$level'
      path: '/$level'
      fullPath: '/dashboard/$program/$level'
      preLoaderRoute: typeof protectedDashboardProgramLevelRouteImport
      parentRoute: typeof protectedDashboardProgramRouteRoute
    }
    '/preview/dashboard/$program/': {
      id: '/preview/dashboard/$program/'
      path: '/'
      fullPath: '/preview/dashboard/$program/'
      preLoaderRoute: typeof PreviewDashboardProgramIndexRouteImport
      parentRoute: typeof PreviewDashboardProgramRouteRoute
    }
    '/preview/dashboard/$program/$level': {
      id: '/preview/dashboard/$program/$level'
      path: '/$level'
      fullPath: '/preview/dashboard/$program/$level'
      preLoaderRoute: typeof PreviewDashboardProgramLevelRouteImport
      parentRoute: typeof PreviewDashboardProgramRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authRefIdRoute: typeof authRefIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authRefIdRoute: authRefIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedDashboardProgramRouteRouteChildren {
  protectedDashboardProgramLevelRoute: typeof protectedDashboardProgramLevelRoute
  protectedDashboardProgramIndexRoute: typeof protectedDashboardProgramIndexRoute
}

const protectedDashboardProgramRouteRouteChildren: protectedDashboardProgramRouteRouteChildren =
  {
    protectedDashboardProgramLevelRoute: protectedDashboardProgramLevelRoute,
    protectedDashboardProgramIndexRoute: protectedDashboardProgramIndexRoute,
  }

const protectedDashboardProgramRouteRouteWithChildren =
  protectedDashboardProgramRouteRoute._addFileChildren(
    protectedDashboardProgramRouteRouteChildren,
  )

interface protectedDashboardRouteRouteChildren {
  protectedDashboardProgramRouteRoute: typeof protectedDashboardProgramRouteRouteWithChildren
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardProgramRouteRoute:
      protectedDashboardProgramRouteRouteWithChildren,
    protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

interface protectedPackagePurchaseRouteRouteChildren {
  protectedPackagePurchaseMagicGoldMatrixRoute: typeof protectedPackagePurchaseMagicGoldMatrixRoute
  protectedPackagePurchaseMagicLevelRoute: typeof protectedPackagePurchaseMagicLevelRoute
  protectedPackagePurchaseSponsorMagicRoute: typeof protectedPackagePurchaseSponsorMagicRoute
  protectedPackagePurchaseIndexRoute: typeof protectedPackagePurchaseIndexRoute
}

const protectedPackagePurchaseRouteRouteChildren: protectedPackagePurchaseRouteRouteChildren =
  {
    protectedPackagePurchaseMagicGoldMatrixRoute:
      protectedPackagePurchaseMagicGoldMatrixRoute,
    protectedPackagePurchaseMagicLevelRoute:
      protectedPackagePurchaseMagicLevelRoute,
    protectedPackagePurchaseSponsorMagicRoute:
      protectedPackagePurchaseSponsorMagicRoute,
    protectedPackagePurchaseIndexRoute: protectedPackagePurchaseIndexRoute,
  }

const protectedPackagePurchaseRouteRouteWithChildren =
  protectedPackagePurchaseRouteRoute._addFileChildren(
    protectedPackagePurchaseRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  protectedLeaderboardRouteRoute: typeof protectedLeaderboardRouteRoute
  protectedLinksRouteRoute: typeof protectedLinksRouteRoute
  protectedPackagePurchaseRouteRoute: typeof protectedPackagePurchaseRouteRouteWithChildren
  protectedPartnersRouteRoute: typeof protectedPartnersRouteRoute
  protectedSocialRouteRoute: typeof protectedSocialRouteRoute
  protectedStatsRouteRoute: typeof protectedStatsRouteRoute
  protectedTeamRouteRoute: typeof protectedTeamRouteRoute
  protectedIncomeMagicGoldMatrixRoute: typeof protectedIncomeMagicGoldMatrixRoute
  protectedIncomeMagicLevelRoute: typeof protectedIncomeMagicLevelRoute
  protectedIncomeSponsorMagicRoute: typeof protectedIncomeSponsorMagicRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  protectedLeaderboardRouteRoute: protectedLeaderboardRouteRoute,
  protectedLinksRouteRoute: protectedLinksRouteRoute,
  protectedPackagePurchaseRouteRoute:
    protectedPackagePurchaseRouteRouteWithChildren,
  protectedPartnersRouteRoute: protectedPartnersRouteRoute,
  protectedSocialRouteRoute: protectedSocialRouteRoute,
  protectedStatsRouteRoute: protectedStatsRouteRoute,
  protectedTeamRouteRoute: protectedTeamRouteRoute,
  protectedIncomeMagicGoldMatrixRoute: protectedIncomeMagicGoldMatrixRoute,
  protectedIncomeMagicLevelRoute: protectedIncomeMagicLevelRoute,
  protectedIncomeSponsorMagicRoute: protectedIncomeSponsorMagicRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface PreviewDashboardProgramRouteRouteChildren {
  PreviewDashboardProgramLevelRoute: typeof PreviewDashboardProgramLevelRoute
  PreviewDashboardProgramIndexRoute: typeof PreviewDashboardProgramIndexRoute
}

const PreviewDashboardProgramRouteRouteChildren: PreviewDashboardProgramRouteRouteChildren =
  {
    PreviewDashboardProgramLevelRoute: PreviewDashboardProgramLevelRoute,
    PreviewDashboardProgramIndexRoute: PreviewDashboardProgramIndexRoute,
  }

const PreviewDashboardProgramRouteRouteWithChildren =
  PreviewDashboardProgramRouteRoute._addFileChildren(
    PreviewDashboardProgramRouteRouteChildren,
  )

interface PreviewDashboardRouteRouteChildren {
  PreviewDashboardProgramRouteRoute: typeof PreviewDashboardProgramRouteRouteWithChildren
  PreviewDashboardIndexRoute: typeof PreviewDashboardIndexRoute
}

const PreviewDashboardRouteRouteChildren: PreviewDashboardRouteRouteChildren = {
  PreviewDashboardProgramRouteRoute:
    PreviewDashboardProgramRouteRouteWithChildren,
  PreviewDashboardIndexRoute: PreviewDashboardIndexRoute,
}

const PreviewDashboardRouteRouteWithChildren =
  PreviewDashboardRouteRoute._addFileChildren(
    PreviewDashboardRouteRouteChildren,
  )

interface PreviewRouteRouteChildren {
  PreviewDashboardRouteRoute: typeof PreviewDashboardRouteRouteWithChildren
  PreviewLeaderboardRouteRoute: typeof PreviewLeaderboardRouteRoute
  PreviewLinksRouteRoute: typeof PreviewLinksRouteRoute
  PreviewPartnersRouteRoute: typeof PreviewPartnersRouteRoute
  PreviewTeamRouteRoute: typeof PreviewTeamRouteRoute
  PreviewIncomeMagicGoldMatrixRoute: typeof PreviewIncomeMagicGoldMatrixRoute
  PreviewIncomeMagicLevelRoute: typeof PreviewIncomeMagicLevelRoute
  PreviewIncomeSponsorMagicRoute: typeof PreviewIncomeSponsorMagicRoute
}

const PreviewRouteRouteChildren: PreviewRouteRouteChildren = {
  PreviewDashboardRouteRoute: PreviewDashboardRouteRouteWithChildren,
  PreviewLeaderboardRouteRoute: PreviewLeaderboardRouteRoute,
  PreviewLinksRouteRoute: PreviewLinksRouteRoute,
  PreviewPartnersRouteRoute: PreviewPartnersRouteRoute,
  PreviewTeamRouteRoute: PreviewTeamRouteRoute,
  PreviewIncomeMagicGoldMatrixRoute: PreviewIncomeMagicGoldMatrixRoute,
  PreviewIncomeMagicLevelRoute: PreviewIncomeMagicLevelRoute,
  PreviewIncomeSponsorMagicRoute: PreviewIncomeSponsorMagicRoute,
}

const PreviewRouteRouteWithChildren = PreviewRouteRoute._addFileChildren(
  PreviewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  PreviewRouteRoute: PreviewRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
